version: "3.7"

services:
  ruby_dev:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    depends_on:
      - pets_db

  pets_db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
      
volumes:
  db-data:
